#!/usr/bin/env python3
"""
SERVAL Acquisition GUI

PyQt GUI for SERVAL detector control and TPX3 data acquisition
with real-time histogram visualization and multiple TOF ROI filters.

Uses dock widgets for flexible layout with dynamic ROI image panels.

Usage:
    python -m SERVAL.gui.acquisition_gui
"""

import os
import sys
import threading
import time
from datetime import datetime
from pathlib import Path

# Register PyServal's extra Material Icons into Qt's resource system before any
# create_icon() call.  The file is generated by:  python -m SERVAL.resources.build_icons
try:
    import SERVAL.resources.material_icons.resources.icons_rounded_40  # noqa: F401
except ModuleNotFoundError:
    pass  # not yet generated; icons will fall back to text labels

import numpy as np
from pyqtgraph.dockarea import DockArea, Dock
from qtpy.QtCore import QObject, Qt, QSettings, QTimer, Signal
from qtpy.QtWidgets import (
    QActionGroup,
    QApplication,
    QDoubleSpinBox,
    QToolBar,
    QHBoxLayout,
    QLabel,
    QLineEdit,
    QMainWindow,
    QMenu,
    QMessageBox,
    QPushButton,
    QSizePolicy,
    QStatusBar,
    QToolButton,
    QVBoxLayout,
    QWidget,
)

from pymodaq_gui.managers.action_manager import ActionManager
from pymodaq_gui.managers.parameter_manager import ParameterManager
from pymodaq_gui.utils.styling import create_icon

from SERVAL.controllers.serval_control import SERVALController
from SERVAL.core.data_types import TDCChannel, TriggerEdge
from SERVAL.gui.histogram_controller import HistogramController
from SERVAL.gui.image_dock_widget import ImageDockWidget
from SERVAL.gui.log_dock import LogDock
from SERVAL.gui.pipeline_status_dock import PipelineStatusDock
from SERVAL.gui.pipeline_thread import PipelineThread
from SERVAL.gui.roi_manager import ROIManager
from SERVAL.gui.tof_histogram_dock import TofHistogramDock
from SERVAL.utils.logging import (
    add_log_handler, get_logger, remove_log_handler,
    enable_file_logging, disable_file_logging,set_log_level
)

# Log a per-step timing breakdown of _update_histograms() when the total
# exceeds this many milliseconds. Visible at DEBUG level (set_log_level('DEBUG')).
_SLOW_REFRESH_MS = 20.0
set_log_level('DEBUG')
class _ServalSignaller(QObject):
    """Helper QObject for cross-thread signal delivery from the SERVAL config thread."""
    started = Signal()
    failed = Signal(str)


class ServalAcquisitionGUI(QMainWindow, ParameterManager, ActionManager):
    """
    Main GUI for SERVAL acquisition with live histograms.

    Components
    ----------
    tof_dock : TofHistogramDock
        TOF histogram plot, display settings, and ROI table.
    roi_manager : ROIManager
        Manages TOF ROI regions and their image docks.
    total_dock : ImageDockWidget
        Accumulated 2-D pixel histogram.
    histogram : HistogramController
        In-process accumulator for pixel/event data.
    pipeline_thread : PipelineThread | None
        Background thread running TPX3PipelineV3.
    """

    settings_name = 'serval_acquisition'
    params = [
        {'title': 'SERVAL', 'name': 'serval', 'type': 'group', 'children': [
            {'title': 'Connection', 'name': 'serval_connection', 'type': 'action_led', 'children': [
                {'title': 'Host', 'name': 'host', 'type': 'str', 'value': '192.168.1.1',
                 'tip': 'IP address of the SERVAL server'},
                {'title': 'Port', 'name': 'port', 'type': 'int', 'value': 8080,
                 'limits': (1, 65535), 'tip': 'SERVAL HTTP REST API port (default 8080)'},
            ]},
            {'title': 'Destination', 'name': 'serval_destination', 'type': 'action_led', 'children': [
                {'title': 'Dest. Host', 'name': 'dest_host', 'type': 'str', 'value': '192.168.1.2',
                 'tip': 'IP address of this machine as seen from the SERVAL server'},
                {'title': 'Dest. Port', 'name': 'dest_port', 'type': 'int', 'value': 8088,
                 'limits': (1, 65535), 'tip': 'TCP port on which the pipeline listens for incoming data'},
                {'title': 'Advanced', 'name': 'advanced', 'type': 'group', 'children': [
                    {'title': 'Chunk Size (B)', 'name': 'chunk_size', 'type': 'int',
                     'value': 10_000_000, 'limits': (100_000, 100_000_000),
                     'tip': 'Flush data to extractors after this many bytes (larger = higher latency, better throughput)'},
                    {'title': 'Flush Timeout (s)', 'name': 'flush_timeout', 'type': 'float',
                     'value': 0.3, 'limits': (0.01, 5.0),
                     'tip': 'Force flush after this many seconds even if chunk size not reached'},
                    {'title': 'Recv Buffer (MB)', 'name': 'recv_buffer_mb', 'type': 'int',
                     'value': 2, 'limits': (1, 512),
                     'tip': 'OS-level TCP receive buffer size — increase if seeing dropped chunks at high rates'},
                ]},
            ]},
            {'title': 'Voltage', 'name': 'voltage_settings', 'type': 'action_led', 'children': [
                {'title': 'Bias Voltage (V)', 'name': 'bias_voltage', 'type': 'int',
                 'value': 40, 'limits': (0, 200),
                 'tip': 'Sensor bias voltage. Typical range 40–100 V. Apply with the Voltage button.'},
                {'title': 'Bias Enabled', 'name': 'bias_enabled', 'type': 'bool', 'value': True,
                 'tip': 'Enable or disable the bias voltage supply'},
            ]},
            {'title': 'Triggers', 'name': 'trigger_settings', 'type': 'action_led', 'children': [
                {'title': 'Trigger Mode', 'name': 'trigger_mode', 'type': 'list',
                 'limits': ['CONTINUOUS', 'AUTOTRIGSTART_TIMERSTOP', 'EXTERNAL'
                 'PEXSTART_NEXSTOP', 'NEXSTART_PEXSTOP', 'PEXSTART_TIMERSTOP', 'NEXSTART_TIMERSTOP',
                 ],
                 'value': 'CONTINUOUS',
                 'tip': ('CONTINUOUS: free-running, no trigger correlation.\n'
                         'AUTOTRIGSTART_TIMERSTOP: internal timer generates triggers at Period/Exposure.\n'
                         'EXTERNAL: triggers come from the TDC input (hardware signal required).\n'
                         'PEXSTART_NEXSTOP: Acq. is started by positive edge external trigger input, stopped by negative edge.\n'
                         'NEXSTART_PEXSTOP: Acq. is started by negative edge external trigger input, stopped by positive edge.\n'
                         'PEXSTART_TIMERSTOP: Acq. is started by positive edge external trigger input, stopped by HW timer.\n'
                         'NEXSTART_TIMERSTOP: Acq. is started by negative edge external trigger input, stopped by HW timer.\n'
                         )},
                {'title': 'N Triggers', 'name': 'n_triggers', 'type': 'int', 'value': -1,
                 'limits': (-1, 1000000), 'tip': 'Number of triggers before auto-stop. -1 = unlimited.'},
                {'title': 'Period (s)', 'name': 'trigger_period', 'type': 'float',
                 'value': 0.5, 'limits': (0.001, 1000.0),
                 'tip': 'Time between trigger starts (AUTOTRIGSTART_TIMERSTOP mode only)'},
                {'title': 'Exposure (s)', 'name': 'trigger_exposure', 'type': 'float',
                 'value': 0.01, 'limits': (0.0001, 100.0),
                 'tip': 'Active acquisition window per trigger (AUTOTRIGSTART_TIMERSTOP mode only)'},
            ]},
        ]},
        {'title': 'Pipeline', 'name': 'pipeline', 'type': 'group', 'children': [
            {'title': 'Processing', 'name': 'processing', 'type': 'group', 'children': [
                {'title': 'Workers', 'name': 'num_workers', 'type': 'int', 'value': 4,
                 'limits': (1, 16),
                 'tip': 'Number of parallel extractor processes. Match to available CPU cores.'},
                {'title': 'Fast Extract', 'name': 'use_fast_extract', 'type': 'bool',
                 'value': True,
                 'tip': 'Use optimised (Numba JIT) extraction path. Disable only for debugging.'},
                {'title': 'TDC', 'name': 'tdc_id', 'type': 'list',
                 'limits': TDCChannel.labels(), 'value': TDCChannel.TDC1.label,
                 'tip': 'TDC channel carrying the trigger signal used for TOF correlation'},
                {'title': 'Edge', 'name': 'edge', 'type': 'list',
                 'limits': TriggerEdge.labels(), 'value': TriggerEdge.RISING.label,
                 'tip': 'Which edge of the TDC signal marks the trigger time (Rising or Falling)'},
                {'title': 'Event Window Min (ns)', 'name': 'event_window_min', 'type': 'float',
                 'value': 0.0,
                 'tip': 'Minimum TOF for a pixel to be correlated to a trigger (ns)'},
                {'title': 'Event Window Max (ns)', 'name': 'event_window_max', 'type': 'float',
                 'value': 100000.0,
                 'tip': 'Maximum TOF for a pixel to be correlated to a trigger (ns)'},
                {'title': 'Centroiding', 'name': 'centroiding', 'type': 'group', 'children': [
                    {'title': 'Enable', 'name': 'use_centroiding', 'type': 'bool', 'value': False,
                     'tip': 'Cluster neighbouring pixel hits into single events (reduces charge sharing artefacts)'},
                    {'title': 'Spatial eps (px)', 'name': 'eps_space', 'type': 'int',
                     'value': 2, 'limits': (1, 10),
                     'tip': 'Maximum pixel distance between hits in the same cluster'},
                    {'title': 'Time eps (ns)', 'name': 'eps_time_ns', 'type': 'float',
                     'value': 100.0, 'limits': (1.0, 10000.0), 'step': 1.0, 'decimals': 0,
                     'tip': 'Maximum time difference between hits in the same cluster (ns)'},
                    {'title': 'Buffer depth', 'name': 'b_size', 'type': 'int',
                     'value': 16, 'limits': (4, 128),
                     'tip': 'Number of hits buffered per worker for cluster search'},
                ]},
                {'title': 'Advanced', 'name': 'advanced', 'type': 'group', 'children': [
                    {'title': 'ZMQ Port', 'name': 'zmq_port', 'type': 'int', 'value': 9200,
                     'limits': (1024, 65535),
                     'tip': 'Internal ZMQ port used between TCP receiver and extractor workers'},
                    {'title': 'ZMQ HWM', 'name': 'zmq_hwm', 'type': 'int', 'value': 1000,
                     'limits': (10, 100000),
                     'tip': 'ZMQ high-water mark — max queued messages before chunks are dropped'},
                ]},
            ]},
            {'title': 'Saving', 'name': 'saving', 'type': 'group', 'children': [
                {'title': 'Output Directory', 'name': 'output_dir', 'type': 'str',
                 'value': './data',
                 'tip': 'Root directory for saved data. Each recording creates a timestamped subdirectory here.'},
                {'title': 'Save Raw', 'name': 'save_raw', 'type': 'bool', 'value': True,
                 'tip': 'Write raw TPX3 binary stream to .tpx3 file (needed to reprocess offline)'},
                {'title': 'Save Events', 'name': 'save_events', 'type': 'bool', 'value': True,
                 'tip': 'Write correlated TOF events to _events.dat (numpy structured array)'},
                {'title': 'Save Pixels', 'name': 'save_pixels', 'type': 'bool', 'value': False,
                 'tip': 'Write uncorrelated pixel hits to _pixels.dat (numpy structured array)'},
                {'title': 'Save Triggers', 'name': 'save_triggers', 'type': 'bool', 'value': True,
                 'tip': 'Write TDC trigger timestamps to _triggers.dat'},
                {'title': 'Advanced', 'name': 'advanced', 'type': 'group', 'children': [
                    {'title': 'Raw Savers', 'name': 'raw_num_savers', 'type': 'int',
                     'value': 1, 'limits': (0, 4),
                     'tip': 'Number of parallel processes writing raw data (0 disables raw saving)'},
                    {'title': 'Events Savers', 'name': 'events_num_savers', 'type': 'int',
                     'value': 2, 'limits': (0, 8),
                     'tip': 'Number of parallel processes writing event data'},
                    {'title': 'Pixels Savers', 'name': 'pixels_num_savers', 'type': 'int',
                     'value': 1, 'limits': (0, 4),
                     'tip': 'Number of parallel processes writing pixel data'},
                    {'title': 'Triggers Savers', 'name': 'triggers_num_savers', 'type': 'int',
                     'value': 1, 'limits': (0, 4),
                     'tip': 'Number of parallel processes writing trigger data'},
                ]},
            ]},
            {'title': 'Live', 'name': 'live', 'type': 'group', 'children': [
                {'title': 'Callback Mode', 'name': 'callback_mode', 'type': 'list',
                 'limits': ['events', 'pixels', 'disabled'], 'value': 'events',
                 'tip': 'What data the pipeline sends to the GUI for live display. Disable to reduce overhead.'},
                {'title': 'Command Server', 'name': 'command_server', 'type': 'group', 'children': [
                    {'title': 'Enable', 'name': 'cmd_enabled', 'type': 'bool', 'value': True,
                     'tip': 'Enable ZMQ command server for external control (e.g. from PyMoDAQ)'},
                    {'title': 'Port', 'name': 'cmd_port', 'type': 'int', 'value': 9100,
                     'limits': (1024, 65535),
                     'tip': 'ZMQ port for the command server'},
                ]},
            ]},
        ]},
    ]

    def __init__(self):
        QMainWindow.__init__(self)
        ParameterManager.__init__(self, action_list=('search', 'save', 'load'))
        ActionManager.__init__(self)

        self.setWindowTitle("SERVAL Acquisition")
        self.setMinimumSize(1200, 800)
        self.resize(1600, 1000)

        # Core objects
        self.serval = SERVALController()
        self.histogram = HistogramController()
        self.pipeline_thread = None

        self._gui_logger = get_logger('SERVAL.GUI')
        # self._gui_logger.setLevel("DEBUG")
        # State
        self.is_acquiring = False
        self._is_recording = False
        self._display_mode = 'events'   # 'events' (TOF) | 'pixels' (TOA)
        self._lag_ms = None  # end-to-end latency (extraction -> GUI), updated per batch

        # Cross-thread signal helper
        self._serval_sig = _ServalSignaller()
        self._serval_sig.started.connect(self._on_serval_started)
        self._serval_sig.failed.connect(self._on_pipeline_error)

        # Timers
        self.refresh_timer = QTimer()
        self.refresh_timer.timeout.connect(self._update_histograms)

        self._save_timer = QTimer()
        self._save_timer.setSingleShot(True)
        self._save_timer.timeout.connect(self._auto_stop_save)

        self._last_clear_time = None

        # Build UI
        self._setup_toolbar()
        self._create_recording_toolbar()
        self._setup_ui()
        self._connect_signals()

        # Status bar
        self.status_bar = QStatusBar()
        self.setStatusBar(self.status_bar)
        self._build_status_leds()
        self.status_bar.showMessage("Ready")

        self._restore_session()

        # Keep toolbar toggles in sync when the recording toolbar is closed
        self._recording_toolbar.visibilityChanged.connect(
            lambda v: self.get_action('show_recording').setChecked(v))

    # =========================================================================
    # ParameterManager hook
    # =========================================================================
    def value_changed(self, param):
        pass

    # =========================================================================
    # Display parameter — convenience property
    # =========================================================================
    @property
    def display(self):
        """Shortcut to TofHistogramDock's display Parameter group."""
        return self.tof_dock.display

    # =========================================================================
    # Status bar LEDs
    # =========================================================================
    def _build_status_leds(self):
        for name, label in [('led_connected', 'SERVAL'),
                             ('led_acquiring', 'ACQ'),
                             ('led_recording', 'REC')]:
            led = QLabel(f'● {label}')
            led.setStyleSheet('color: #555555; font-weight: bold; padding: 0 6px;')
            self.status_bar.addPermanentWidget(led)
            setattr(self, name, led)

    def _set_led(self, led: QLabel, active: bool, color: str = '#44cc44'):
        col = color if active else '#555555'
        led.setStyleSheet(f'color: {col}; font-weight: bold; padding: 0 6px;')

    # =========================================================================
    # ActionManager
    # =========================================================================
    def setup_actions(self):
        self.add_action('show_settings', 'Settings', 'settings',
                        tip='Show/hide settings panel',
                        checkable=True, checked=True, shortcut='F1', auto_toolbar=False,
                        icon_checked_color='green')
        self.add_action('connect', 'Connect', 'cable',
                        tip='Connect / Disconnect SERVAL',
                        checkable=True, shortcut='F2', auto_toolbar=False,
                        icon_checked_color='green')
        self.add_action('run', 'Run', 'motion_play',
                        tip='Start / Stop acquisition', shortcut='F5', auto_toolbar=False,
                        checkable=True, icon_checked_color='green')
        self.add_action('show_tof_dock', 'TOF', 'bar_chart',
                        tip='Show/hide the TOF histogram dock',
                        checkable=True, checked=True, auto_toolbar=False,
                        icon_checked_color='green')
        self.add_action('show_total_dock', 'Image', 'image',
                        tip='Show/hide the Total 2D image dock',
                        checkable=True, checked=True, auto_toolbar=False,
                        icon_checked_color='green')
        self.add_action('show_recording', 'Recording', 'hard_drive',
                        tip='Show/hide recording controls',
                        checkable=True, checked=False, auto_toolbar=False,
                        icon_checked_color='green')
        self.add_action('show_log', 'Log', 'format_list_bulleted',
                        tip='Show/hide log panel',
                        checkable=True, auto_toolbar=False,
                        icon_checked_color='green')
        self.add_action('show_pipeline_status', 'Status', 'analytics',
                        tip='Show/hide pipeline status panel (queues & workers)',
                        checkable=True, auto_toolbar=False,
                        icon_checked_color='green')

    def _setup_toolbar(self):
        self.setup_actions()
        tb = self.addToolBar('Acquisition')
        tb.setMovable(False)

        tb.addAction(self.get_action('show_settings'))
        tb.addSeparator()
        tb.addAction(self.get_action('connect'))
        tb.addSeparator()
        tb.addAction(self.get_action('run'))
        tb.addSeparator()
        tb.addAction(self.get_action('show_tof_dock'))
        tb.addAction(self.get_action('show_total_dock'))
        tb.addSeparator()
        tb.addAction(self.get_action('show_recording'))
        tb.addAction(self.get_action('show_log'))
        tb.addAction(self.get_action('show_pipeline_status'))

        self.get_action('run').setEnabled(False)

        # Spacer pushes the view-options button to the far right
        spacer = QWidget()
        spacer.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Preferred)
        tb.addWidget(spacer)

        self._build_toolbar_style_button(tb)

        self.get_action('show_settings').connect_to(
            lambda v: self._settings_dock.show() if v else self._settings_dock.hide())
        self.get_action('connect').connect_to(self._on_connect_clicked)
        self.get_action('run').connect_to(self._on_run_clicked)
        self.get_action('show_tof_dock').connect_to(
            lambda v: self.tof_dock.show() if v else self.tof_dock.hide())
        self.get_action('show_total_dock').connect_to(
            lambda v: self.total_dock.show() if v else self.total_dock.hide())
        self.get_action('show_recording').connect_to(
            lambda v: self._recording_toolbar.setVisible(v))
        self.get_action('show_log').connect_to(
            lambda v: self.log_dock.show() if v else self.log_dock.hide())
        self.get_action('show_pipeline_status').connect_to(
            lambda v: self._status_dock.show() if v else self._status_dock.hide())

    # ── Toolbar style ─────────────────────────────────────────────────────────

    _TOOLBAR_STYLES = [
        ('Icons only',        Qt.ToolButtonStyle.ToolButtonIconOnly),
        ('Text only',         Qt.ToolButtonStyle.ToolButtonTextOnly),
        ('Text beside icons', Qt.ToolButtonStyle.ToolButtonTextBesideIcon),
        ('Text under icons',  Qt.ToolButtonStyle.ToolButtonTextUnderIcon),
        ('System settings',  Qt.ToolButtonStyle.ToolButtonFollowStyle),
    ]

    def _apply_toolbar_style(self, style: Qt.ToolButtonStyle):
        """Apply *style* to every QToolBar in the application and persist it."""
        from qtpy.QtWidgets import QToolBar as _QToolBar
        for widget in QApplication.instance().allWidgets():
            if isinstance(widget, _QToolBar):
                widget.setToolButtonStyle(style)
        # .value handles Qt6 enums; plain int() covers Qt5 sip ints
        style_int = style.value if hasattr(style, 'value') else int(style)
        self._qsettings().setValue('toolbar_style', style_int)

    def _build_toolbar_style_button(self, tb):
        """Add a view-options QToolButton (far right) for toolbar display style."""
        btn = QToolButton()
        btn.setIcon(create_icon('explicit'))
        btn.setToolTip("Toolbar display style")
        btn.setPopupMode(QToolButton.ToolButtonPopupMode.InstantPopup)

        menu = QMenu(btn)
        self._toolbar_style_group = QActionGroup(menu)
        self._toolbar_style_group.setExclusive(True)

        for label, style in self._TOOLBAR_STYLES:
            act = menu.addAction(label)
            act.setCheckable(True)
            act.setActionGroup(self._toolbar_style_group)
            act.triggered.connect(
                lambda _checked, s=style: self._apply_toolbar_style(s))

        btn.setMenu(menu)
        tb.addWidget(btn)

    # =========================================================================
    # UI Setup
    # =========================================================================
    def _setup_ui(self):
        # DockArea as central widget
        self.dock_area = DockArea()
        self.setCentralWidget(self.dock_area)

        # Left: Settings
        self._create_settings_dock()

        # Centre: TOF histogram dock
        self.tof_dock = TofHistogramDock()
        self.dock_area.addDock(self.tof_dock, 'right', self._settings_dock)

        # Right: Total 2D image
        self.total_dock = ImageDockWidget("Total")
        self.total_dock.timeseries_check.setChecked(True)
        self.dock_area.addDock(self.total_dock, 'right', self.tof_dock)

        # Bottom: Log (hidden by default)
        self.log_dock = LogDock()
        self.dock_area.addDock(self.log_dock, 'bottom')
        self.log_dock.hide()
        add_log_handler(self.log_dock.handler)

        # Bottom: Pipeline status (hidden by default)
        self._status_dock = PipelineStatusDock()
        self.dock_area.addDock(self._status_dock, 'bottom')
        self._status_dock.hide()

        # ROI manager (composition, not inheritance)
        self.roi_manager = ROIManager(
            tof_plot=self.tof_dock.tof_plot,
            roi_table=self.tof_dock.roi_table,
            display=self.tof_dock.display,
            main_window=self,
            dock_area=self.dock_area,
            total_dock=self.total_dock,
            parent=self,
        )

    def _create_settings_dock(self):
        self._settings_dock = Dock("Settings", closable=False, size=(350, 800))
        widget = QWidget()
        layout = QVBoxLayout(widget)
        layout.setContentsMargins(5, 5, 5, 5)
        layout.addWidget(self.settings_tree, stretch=1)
        self._settings_dock.addWidget(widget)
        self.dock_area.addDock(self._settings_dock, 'left')

    def _create_recording_toolbar(self):
        self.addToolBarBreak(Qt.ToolBarArea.TopToolBarArea)
        tb = QToolBar("Recording", self)
        tb.setObjectName('recording_toolbar')
        self.addToolBar(Qt.ToolBarArea.TopToolBarArea, tb)

        tb.addWidget(QLabel("  Name:"))
        self.record_filename_edit = QLineEdit()
        self.record_filename_edit.setPlaceholderText("auto-timestamp")
        self.record_filename_edit.setToolTip("Save filename (no extension)")
        self.record_filename_edit.setMinimumWidth(160)
        tb.addWidget(self.record_filename_edit)

        tb.addWidget(QLabel("  Duration (s):"))
        self.save_duration_spin = QDoubleSpinBox()
        self.save_duration_spin.setRange(0.0, 86400.0)
        self.save_duration_spin.setSingleStep(0.5)
        self.save_duration_spin.setValue(0.0)
        self.save_duration_spin.setDecimals(1)
        self.save_duration_spin.setToolTip("0 = manual stop")
        self.save_duration_spin.setSpecialValueText("Manual")
        self.save_duration_spin.setFixedWidth(90)
        tb.addWidget(self.save_duration_spin)

        self.record_btn = QPushButton("Save")
        self.record_btn.clicked.connect(self._on_save_clicked)
        self.record_btn.setEnabled(False)
        self.record_btn.setFixedWidth(70)
        tb.addWidget(self.record_btn)

        tb.addSeparator()
        self.stats_label = QLabel("Events: 0")
        self.stats_label.setStyleSheet("font-family: monospace;")
        tb.addWidget(self.stats_label)

        self._recording_toolbar = tb

    # =========================================================================
    # Signal Connections
    # =========================================================================
    def _connect_signals(self):
        # SERVAL controller
        self.settings.child("serval", "serval_connection").sigActivated.connect(
            self._on_connect_clicked)
        self.settings.child("serval", "voltage_settings").sigActivated.connect(
            self._on_apply_bias)
        self.settings.child("serval", "trigger_settings").sigActivated.connect(
            self._on_apply_triggers)
        self.serval.connected.connect(self._on_serval_connected)
        self.serval.disconnected.connect(self._on_serval_disconnected)
        self.serval.error_occurred.connect(self._on_serval_error)

        # TOF histogram dock
        self.tof_dock.clear_requested.connect(self._on_clear_all)
        self.tof_dock.display.sigTreeStateChanged.connect(self._on_display_param_changed)

        # ROI dock mini-toolbar → ROIManager
        self.tof_dock.add_roi_clicked.connect(self.roi_manager.add_roi)
        self.tof_dock.remove_roi_clicked.connect(self.roi_manager.remove_roi)
        self.tof_dock.raise_roi_clicked.connect(self.roi_manager.raise_selected)
        self.tof_dock.zoom_roi_clicked.connect(self.roi_manager.zoom_to_selected)
        self.tof_dock.zoom_out_clicked.connect(self.roi_manager.zoom_out)

        # ROIManager data-flow → HistogramController
        self.roi_manager.roi_added.connect(
            lambda name, mn, mx: self.histogram.add_roi(name, mn, mx))
        self.roi_manager.roi_removed.connect(self.histogram.remove_roi)
        self.roi_manager.roi_changed.connect(self.histogram.update_roi)

    # =========================================================================
    # Display parameter changes
    # =========================================================================
    def _on_display_param_changed(self, _root, changes):
        for param, _change, _data in changes:
            name = param.name()
            if name == 'refresh_rate_s':
                if self.is_acquiring:
                    self.refresh_timer.start(int(param.value() * 1000))
            elif name == 'clear_interval':
                if self.is_acquiring and param.value() > 0:
                    self._last_clear_time = time.time()
            elif name == 'colormap':
                self._on_colormap_changed(param.value())
            elif name in ('tof_bins', 'tof_min_ns', 'tof_max_ns'):
                self._on_tof_config_changed()
            elif name == 'display_fraction':
                if self.pipeline_thread is not None:
                    self.pipeline_thread.set_display_fraction(param.value() / 100.0)

    def _on_clear_all(self):
        self.histogram.clear()
        self.histogram.clear_timeseries()
        self._update_histograms()
        self._log("Histograms and time series cleared")

    def _on_colormap_changed(self, name: str):
        self.total_dock.set_colormap(name)
        self.roi_manager.set_colormap(name)

    def _on_tof_config_changed(self):
        tof_bins = self.display.child('tof_bins').value()
        tof_min  = self.display.child('tof_min_ns').value()
        tof_max  = self.display.child('tof_max_ns').value()
        self.histogram.set_tof_config(tof_range=(tof_min, tof_max), tof_bins=tof_bins)
        self._update_histograms()

    def _apply_display_mode(self, mode: str):
        """Update plot titles and axis labels to match display mode."""
        if mode == 'pixels':
            self.tof_dock.set_plot_title("Time of Arrival (TOA)")
            self.tof_dock.set_x_label("TOA (ns)")
            ts_label = "Counts/Refresh"
        else:
            self.tof_dock.set_plot_title("Time of Flight (TOF)")
            self.tof_dock.set_x_label("TOF (ns)")
            ts_label = "Counts/Shot"
        self.total_dock.set_timeseries_label(ts_label)
        self.roi_manager.set_timeseries_label(ts_label)

    # =========================================================================
    # SERVAL Handlers
    # =========================================================================
    def _on_connect_clicked(self):
        if self.serval.is_connected:
            self.serval.disconnect()
        else:
            host = self.settings.child('serval', 'serval_connection', 'host').value()
            port = self.settings.child('serval', 'serval_connection', 'port').value()
            self.serval.host = host
            self.serval.port = port
            self.serval.base_url = f'http://{host}:{port}'
            self._log(f"Connecting to {host}:{port}...")
            self.serval.connect()

    def _on_serval_connected(self):
        self.settings.child('serval', 'serval_connection').setValue(self.serval.is_connected)
        self.get_action('connect').setChecked(True)
        self.get_action('run').setEnabled(True)
        self._set_led(self.led_connected, True)
        if self.is_acquiring:
            self.record_btn.setEnabled(True)
        self._log("Connected to SERVAL")

    def _on_serval_disconnected(self):
        self.settings.child('serval', 'serval_connection').setValue(self.serval.is_connected)
        self.get_action('connect').setChecked(False)
        self.get_action('run').setEnabled(False)
        self._set_led(self.led_connected, False)
        self.record_btn.setEnabled(False)
        self._log("Disconnected from SERVAL")

    def _on_serval_error(self, msg: str):
        self._log(f"SERVAL error: {msg}", level=40)

    def _on_apply_bias(self):
        s = self.settings.child('serval', 'voltage_settings')
        voltage = s['bias_voltage']
        enabled = s['bias_enabled']
        success = self.serval.set_bias(voltage, enabled)
        self._log(f"Bias: {voltage}V (enabled={enabled})" if success
                  else "Failed to set bias", level=20 if success else 40)
        s.setValue(success)

    def _on_apply_triggers(self):
        s = self.settings.child('serval', 'trigger_settings')
        mode       = s['trigger_mode']
        n_triggers = s['n_triggers']
        period     = s['trigger_period']
        exposure   = s['trigger_exposure']
        success = self.serval.set_trigger_settings(mode, n_triggers, period, exposure)
        self._log(f"Triggers set: {mode}" if success
                  else "Failed to set triggers", level=20 if success else 40)
        s.setValue(success)

    # =========================================================================
    # Pipeline Status — delegated to PipelineStatusDock
    # =========================================================================
    def _on_status_update(self, status_dict: dict):
        self._status_dock.update_throughput(status_dict)

    def _update_pipeline_status(self):
        if self.pipeline_thread is not None:
            self._status_dock.update_queues_and_workers(
                self.pipeline_thread.get_live_status())

    def _reset_pipeline_status(self):
        self._status_dock.reset()

    # =========================================================================
    # Config dict builders
    # =========================================================================
    def _build_connection_config(self):
        s   = self.settings.child('serval', 'serval_destination')
        adv = s.child('advanced')
        return {
            'host': s['dest_host'],
            'port': s['dest_port'],
            'chunk_size': adv['chunk_size'],
            'flush_timeout': adv['flush_timeout'],
            'recv_buffer_size': adv['recv_buffer_mb'] * 1024 * 1024,
        }

    def _build_extract_config(self):
        p   = self.settings.child('pipeline', 'processing')
        c   = p.child('centroiding')
        adv = p.child('advanced')
        return {
            'num_workers':      p['num_workers'],
            'use_fast_extract': p['use_fast_extract'],
            'tdc_id':           TDCChannel.from_label(p['tdc_id']),
            'edge':             TriggerEdge.from_label(p['edge']),
            'event_window':     (p['event_window_min'], p['event_window_max']),
            'use_centroiding':  c['use_centroiding'],
            'eps_space':        c['eps_space'],
            'eps_time_ns':      c['eps_time_ns'],
            'b_size':           c['b_size'],
            'zmq_port':         adv['zmq_port'],
            'zmq_hwm':          adv['zmq_hwm'],
        }

    def _build_save_config(self):
        p   = self.settings.child('pipeline', 'saving')
        adv = p.child('advanced')
        return {
            'output_dir': p['output_dir'],
            'raw':      {'enabled': p['save_raw'],     'num_savers': adv['raw_num_savers']},
            'events':   {'enabled': p['save_events'],  'num_savers': adv['events_num_savers']},
            'pixels':   {'enabled': p['save_pixels'],  'num_savers': adv['pixels_num_savers']},
            'triggers': {'enabled': p['save_triggers'], 'num_savers': adv['triggers_num_savers']},
        }

    def _build_command_config(self):
        s = self.settings.child('pipeline', 'live', 'command_server')
        return {'enabled': s['cmd_enabled'], 'port': s['cmd_port']}

    # =========================================================================
    # Acquisition Control
    # =========================================================================
    def _on_run_clicked(self, checked: bool):
        if checked:
            self._start_acquisition()
        else:
            self._on_stop_clicked()

    def _start_acquisition(self):
        if self.is_acquiring:
            return
        if not self.serval.is_connected:
            QMessageBox.warning(self, "Not Connected",
                                "Please connect to SERVAL first.")
            self.get_action('run').setChecked(False)
            return

        self.histogram.clear()
        self.histogram.clear_timeseries()

        callback_mode = self.settings.child('pipeline', 'live', 'callback_mode').value()
        display_fraction = self.display.child('display_fraction').value() / 100.0

        self.pipeline_thread = PipelineThread(
            connection_config=self._build_connection_config(),
            save_config=self._build_save_config(),
            extract_config=self._build_extract_config(),
            callback_config={
                'mode': callback_mode if callback_mode != 'disabled' else None,
                'display_fraction': display_fraction,
            },
            command_config=self._build_command_config(),
        )
        self.pipeline_thread.event_data_ready.connect(self._on_event_data)
        self.pipeline_thread.pixel_data_ready.connect(self._on_pixel_data)
        self.pipeline_thread.pipeline_started.connect(self._on_pipeline_started)
        self.pipeline_thread.pipeline_stopped.connect(self._on_pipeline_stopped)
        self.pipeline_thread.error_occurred.connect(self._on_pipeline_error)
        self.pipeline_thread.status_changed.connect(self._on_status_update)

        self.pipeline_thread.start()
        self._log("Starting pipeline...")
        self._set_pipeline_controls_enabled(False)

    def _on_pipeline_started(self):
        self._log("TCP socket bound — configuring SERVAL...")
        try:
            p = self.settings.child('pipeline', 'saving')
            log_path = Path(p['output_dir']) / 'serval.log'
            enable_file_logging(log_path)
            self._log(f"Logging to file: {log_path}")
        except Exception as e:
            self._log(f"Could not start file logging: {e}", level=30)
        threading.Thread(target=self._configure_and_start_serval, daemon=True).start()

    def _configure_and_start_serval(self):
        """HTTP configuration — runs in a background thread."""
        s = self.settings.child('serval', 'serval_destination')
        host = s['dest_host']
        port = s['dest_port']

        self._log(f"Setting SERVAL destination → {host}:{port}")
        if not self.serval.set_destination(host, port):
            self._serval_sig.failed.emit("Failed to set SERVAL destination")
            self.pipeline_thread.request_stop()
            return

        self._log("Starting SERVAL measurement...")
        if not self.serval.start_measurement():
            self._serval_sig.failed.emit("Failed to start SERVAL measurement")
            self.pipeline_thread.request_stop()
            return

        self._serval_sig.started.emit()

    def _on_serval_started(self):
        """Called on the main thread after SERVAL HTTP configuration succeeds."""
        self.is_acquiring = True
        self.record_btn.setEnabled(self.serval.is_connected)
        self._set_led(self.led_acquiring, True)
        self._last_clear_time = time.time()
        refresh_rate_s = self.display.child('refresh_rate_s').value()
        if refresh_rate_s > 0:
            self.refresh_timer.start(int(refresh_rate_s * 1000))
        callback_mode = self.settings.child('pipeline', 'live', 'callback_mode').value()
        if callback_mode == 'disabled':
            callback_mode = 'events'
        self._display_mode = callback_mode
        self._apply_display_mode(callback_mode)
        self._log("Acquisition running")

    def _validate_output_dir(self, path: Path) -> bool:
        if not path.exists():
            reply = QMessageBox.question(
                self, "Output Directory",
                f"Directory does not exist:\n{path}\n\nCreate it?",
                QMessageBox.Yes | QMessageBox.No, QMessageBox.Yes,
            )
            if reply == QMessageBox.No:
                return False
            try:
                path.mkdir(parents=True, exist_ok=True)
            except OSError as e:
                QMessageBox.critical(self, "Error", f"Could not create directory:\n{e}")
                return False
        if not os.access(path, os.W_OK):
            QMessageBox.critical(self, "Error",
                                 f"Output directory is not writable:\n{path}")
            return False
        return True

    def _set_record_btn_state(self, recording: bool):
        if recording:
            self.record_btn.setText("Stop")
            self.record_btn.setStyleSheet(
                "QPushButton { font-weight: bold; padding: 6px; }"
                "QPushButton:enabled { background-color: #f44336; color: white; }")
        else:
            self.record_btn.setText("Save")
            self.record_btn.setStyleSheet(
                "QPushButton { font-weight: bold; padding: 6px; }"
                "QPushButton:enabled { background-color: #2196F3; color: white; }")

    def _on_save_clicked(self):
        if not self.is_acquiring or self.pipeline_thread is None:
            return
        if self._is_recording:
            self._save_timer.stop()
            self._stop_save()
        else:
            p = self.settings.child('pipeline', 'saving')
            output_dir = Path(p['output_dir'])
            if not self._validate_output_dir(output_dir):
                return
            filename = self.record_filename_edit.text().strip()
            if not filename:
                filename = datetime.now().strftime("rec_%Y%m%d_%H%M%S")
            ok = self.pipeline_thread.start_record(
                filename=filename,
                save_raw=p['save_raw'],
                save_events=p['save_events'],
                save_pixels=p['save_pixels'],
                save_triggers=p['save_triggers'],
            )
            if ok:
                self._is_recording = True
                self._set_record_btn_state(True)
                self._set_led(self.led_recording, True, color='#ff4444')
                self.record_filename_edit.setEnabled(False)
                self.save_duration_spin.setEnabled(False)
                self._log(f"Recording started: {filename}")
                duration = self.save_duration_spin.value()
                if duration > 0:
                    self._save_timer.start(int(duration * 1000))

    def _auto_stop_save(self):
        if self._is_recording:
            self._stop_save()

    def _stop_save(self):
        if self.pipeline_thread is not None:
            self.pipeline_thread.stop_record()
        self._is_recording = False
        self._set_record_btn_state(False)
        self._set_led(self.led_recording, False)
        self.record_filename_edit.clear()
        self.record_filename_edit.setEnabled(True)
        self.save_duration_spin.setEnabled(True)
        self._log("Recording stopped")

    def _on_stop_clicked(self):
        if not self.is_acquiring:
            return
        if self._is_recording:
            self._save_timer.stop()
            self.pipeline_thread.stop_record()
            self._is_recording = False
        self._log("Stopping acquisition...")
        self.serval.stop_measurement()
        if self.pipeline_thread:
            self.pipeline_thread.request_stop()

    def _on_pipeline_stopped(self):
        disable_file_logging()
        self._reset_pipeline_status()
        self.is_acquiring = False
        self._is_recording = False
        self._save_timer.stop()
        self.record_btn.setEnabled(False)
        self._set_record_btn_state(False)
        self._set_led(self.led_acquiring, False)
        self._set_led(self.led_recording, False)
        self.record_filename_edit.clear()
        self.record_filename_edit.setEnabled(True)
        self.save_duration_spin.setEnabled(True)
        self._set_pipeline_controls_enabled(True)
        self.refresh_timer.stop()
        self._last_clear_time = None
        self._lag_ms = None
        self._log("Acquisition stopped")
        self._update_histograms()

    def _on_pipeline_error(self, msg: str):
        self._log(f"Pipeline error: {msg}", level=40)
        QMessageBox.critical(self, "Pipeline Error", msg)

    @staticmethod
    def _set_group_enabled(param, enabled: bool):
        for child in param.children():
            if child.hasChildren():
                ServalAcquisitionGUI._set_group_enabled(child, enabled)
            else:
                child.setOpts(enabled=enabled)

    def _set_pipeline_controls_enabled(self, enabled: bool):
        self._set_group_enabled(self.settings.child('pipeline'), enabled)
        self._set_group_enabled(
            self.settings.child('serval', 'serval_destination'), enabled)
        self.get_action('run').setChecked(not enabled)

    # =========================================================================
    # Data Handlers
    # =========================================================================
    def _on_event_data(self, event_num, x, y, tof, tot, t_sent):
        if self._display_mode != 'events':
            return
        self._lag_ms = (time.monotonic() - t_sent) * 1000
        self.histogram.add_events(event_num, x, y, tof, tot)

    def _on_pixel_data(self, x, y, toa, tot, t_sent):
        if self._display_mode != 'pixels':
            return
        self._lag_ms = (time.monotonic() - t_sent) * 1000
        self.histogram.add_pixels(x, y, toa, tot)

    def _update_histograms(self):
        t_start = time.perf_counter()

        if self.is_acquiring:
            self.histogram.sample_timeseries()
        t_timeseries = time.perf_counter()

        pixel_data   = self.histogram.get_pixel_image()
        total_counts = int(pixel_data.sum())
        self.total_dock.update_image(pixel_data)
        self.total_dock.update_counts(total_counts)
        if self.total_dock.is_timeseries_visible():
            times, counts = self.histogram.get_timeseries(None)
            self.total_dock.update_timeseries(times, counts)
        t_image = time.perf_counter()

        self.roi_manager.update_displays(self.histogram, total_counts)
        t_roi = time.perf_counter()

        tof_centers, tof_counts = self.histogram.get_tof_histogram()
        self.tof_dock.update_tof(tof_centers, tof_counts)
        t_tof = time.perf_counter()

        stats = self.histogram.get_stats()
        lag_str = f"{self._lag_ms:.0f} ms" if self._lag_ms is not None else "—"
        self.stats_label.setText(
            f"Events: {stats['total_events']:,} | Total: {stats['pixel_sum']:,} | Lag: {lag_str}")

        self._update_pipeline_status()
        t_status = time.perf_counter()

        if self.is_acquiring and self._last_clear_time is not None:
            clear_interval = self.display.child('clear_interval').value()
            if clear_interval > 0 and (time.time() - self._last_clear_time) >= clear_interval:
                self.histogram.clear()
                self._last_clear_time = time.time()
                self._log("Histograms cleared")

        total_ms = (t_status - t_start) * 1000
        if total_ms > _SLOW_REFRESH_MS:
            self._gui_logger.debug(
                f"_update_histograms: {total_ms:.1f} ms total "
                f"(timeseries {(t_timeseries - t_start) * 1000:.1f}, "
                f"image {(t_image - t_timeseries) * 1000:.1f}, "
                f"roi {(t_roi - t_image) * 1000:.1f}, "
                f"tof {(t_tof - t_roi) * 1000:.1f}, "
                f"status {(t_status - t_tof) * 1000:.1f})")

    # =========================================================================
    # Session persistence
    # =========================================================================
    def _qsettings(self) -> QSettings:
        return QSettings('SERVAL', 'AcquisitionGUI')

    def _restore_session(self):
        s = self._qsettings()
        if geom := s.value('geometry'):
            self.restoreGeometry(geom)
        if state := s.value('dockarea_state'):
            try:
                self.dock_area.restoreState(state)
                # Sanity-check: if all main docks ended up hidden, the saved
                # state is stale — drop it and let the default layout stand.
                core_docks = [self._settings_dock, self.tof_dock, self.total_dock]
                if all(not d.isVisible() for d in core_docks):
                    self.dock_area.restoreState(None)
                    s.remove('dockarea_state')
            except Exception:
                s.remove('dockarea_state')  # Discard incompatible saved state
        for child in self.display.children():
            key = f'display/{child.name()}'
            if (val := s.value(key)) is not None:
                try:
                    child.setValue(type(child.value())(val))
                except Exception:
                    pass
        # Toolbar style — applied after all docks are built so every toolbar is covered
        if (saved := s.value('toolbar_style')) is not None:
            restored = Qt.ToolButtonStyle(int(saved))
            self._apply_toolbar_style(restored)
            for act, (_lbl, style) in zip(
                    self._toolbar_style_group.actions(), self._TOOLBAR_STYLES):
                act.setChecked(style == restored)

    def _save_session(self):
        s = self._qsettings()
        s.setValue('geometry', self.saveGeometry())
        s.setValue('dockarea_state', self.dock_area.saveState())
        for child in self.display.children():
            s.setValue(f'display/{child.name()}', child.value())

    # =========================================================================
    # Window Events
    # =========================================================================
    def _log(self, msg: str, level: int = 20):
        self.status_bar.showMessage(msg)
        self._gui_logger.log(level, msg)

    def closeEvent(self, event):
        if self.is_acquiring:
            reply = QMessageBox.question(
                self, "Acquisition Running",
                "Stop acquisition and exit?",
                QMessageBox.StandardButton.Yes | QMessageBox.StandardButton.No,
                QMessageBox.StandardButton.No,
            )
            if reply == QMessageBox.StandardButton.No:
                event.ignore()
                return
            self._on_stop_clicked()
            if self.pipeline_thread:
                self.pipeline_thread.wait(5000)

        self._save_session()
        remove_log_handler(self.log_dock.handler)
        event.accept()


def main():
    import multiprocessing
    multiprocessing.set_start_method('forkserver', force=False)

    app = QApplication(sys.argv)
    app.setStyle('Fusion')
    window = ServalAcquisitionGUI()
    window.show()
    sys.exit(app.exec_())


if __name__ == "__main__":
    main()
