#!/usr/bin/env python3
"""
SERVAL Acquisition GUI

PyQt GUI for SERVAL detector control and TPX3 data acquisition
with real-time histogram visualization and multiple TOF ROI filters.

Uses dock widgets for flexible layout with dynamic ROI image panels.

Usage:
    python -m SERVAL.gui.acquisition_gui
"""

import sys
import time
from pathlib import Path

# Register PyServal's extra Material Icons into Qt's resource system before any
# create_icon() call.  The file is generated by:  python -m SERVAL.resources.build_icons
try:
    import SERVAL.resources.material_icons.resources.icons_rounded_40  # noqa: F401
except ModuleNotFoundError:
    pass  # not yet generated; icons will fall back to text labels

import numpy as np
from pyqtgraph.dockarea import DockArea, Dock
from qtpy.QtCore import QObject, Qt, QTimer, Signal
from qtpy.QtWidgets import (
    QActionGroup,
    QApplication,
    QCheckBox,
    QDoubleSpinBox,
    QToolBar,
    QHBoxLayout,
    QLabel,
    QLineEdit,
    QMainWindow,
    QMenu,
    QMessageBox,
    QPushButton,
    QSizePolicy,
    QStatusBar,
    QToolButton,
    QVBoxLayout,
    QWidget,
)

from pymodaq_gui.managers.action_manager import ActionManager
from pymodaq_gui.managers.parameter_manager import ParameterManager
from pymodaq_gui.utils.styling import create_icon

from SERVAL.controllers.serval_control import SERVALController
from SERVAL.gui.acquisition_params import ACQUISITION_PARAMS
from SERVAL.gui.histogram_controller import HistogramController
from SERVAL.gui.image_dock_widget import ImageDockWidget
from SERVAL.gui.log_dock import LogDock
from SERVAL.gui.pipeline_mixin import _PipelineMixin
from SERVAL.gui.pipeline_status_dock import PipelineStatusDock
from SERVAL.gui.roi_manager import ROIManager
from SERVAL.gui.session_mixin import _SessionMixin
from SERVAL.gui.spatial_roi_manager import SpatialROIManager
from SERVAL.gui.covariance_dock import CovarianceDock
from SERVAL.gui.tof_histogram_dock import TofHistogramDock
from SERVAL.utils.logging import (
    add_log_handler, get_logger, remove_log_handler, set_log_level
)

# Log a per-step timing breakdown of _update_histograms() when the total
# exceeds this many milliseconds. Visible at DEBUG level (set_log_level('DEBUG')).
_SLOW_REFRESH_MS = 20.0

# Param paths (tuples of child names) that remain editable while acquisition is
# running.  Add a path here when its value_changed handler is thread-safe and
# does not require a pipeline restart to take effect.
_LIVE_ADJUSTABLE_PARAMS: list[tuple[str, ...]] = []
set_log_level('DEBUG')


class _ServalSignaller(QObject):
    """Helper QObject for cross-thread signal delivery from the SERVAL config thread."""
    started = Signal()
    failed = Signal(str)


class ServalAcquisitionGUI(QMainWindow, ParameterManager, ActionManager,
                           _SessionMixin, _PipelineMixin):
    """
    Main GUI for SERVAL acquisition with live histograms.

    Components
    ----------
    tof_dock : TofHistogramDock
        TOF histogram plot, display settings, and ROI table.
    roi_manager : ROIManager
        Manages TOF ROI regions and their image docks.
    total_dock : ImageDockWidget
        Accumulated 2-D pixel histogram.
    histogram : HistogramController
        In-process accumulator for pixel/event data.
    pipeline_thread : PipelineThread | None
        Background thread running TPX3PipelineV3.
    """

    settings_name = 'serval_acquisition'
    params = ACQUISITION_PARAMS

    def __init__(self):
        QMainWindow.__init__(self)
        ParameterManager.__init__(self, action_list=('search', 'save', 'load'))
        ActionManager.__init__(self)

        self.setWindowTitle("SERVAL Acquisition")
        self.setMinimumSize(1200, 800)
        self.resize(1600, 1000)

        # Core objects
        self.serval = SERVALController()
        self.histogram = HistogramController()
        self.pipeline_thread = None

        self._gui_logger = get_logger('SERVAL.GUI')
        # self._gui_logger.setLevel("DEBUG")
        # State
        self.is_acquiring = False
        self._is_recording = False
        self._record_start_time = None  # time.monotonic() when recording started
        self._last_record_filename = None  # filename used for the previous recording
        self._display_mode = 'events'   # 'events' (TOF) | 'pixels' (TOA)
        self._lag_ms = None  # end-to-end latency (extraction -> GUI), updated per batch

        # Cross-thread signal helper
        self._serval_sig = _ServalSignaller()
        self._serval_sig.started.connect(self._on_serval_started)
        self._serval_sig.failed.connect(self._on_pipeline_error)

        # Timers
        self.refresh_timer = QTimer()
        self.refresh_timer.timeout.connect(self._update_histograms)

        self._save_timer = QTimer()
        self._save_timer.setSingleShot(True)
        self._save_timer.timeout.connect(self._auto_stop_save)

        self._last_clear_time = None

        # Build UI
        self._setup_toolbar()
        self._create_recording_toolbar()
        self._setup_ui()
        self._connect_signals()

        # Status bar
        self.status_bar = QStatusBar()
        self.setStatusBar(self.status_bar)
        self._build_status_leds()
        self.status_bar.showMessage("Ready")

        self._restore_session()

        # Keep toolbar toggles in sync when the recording toolbar is closed
        self._recording_toolbar.visibilityChanged.connect(
            lambda v: self.get_action('show_recording').setChecked(v))

    # =========================================================================
    # ParameterManager hook
    # =========================================================================
    def value_changed(self, param):
        name = param.name()
        if name == 'cov_enabled':
            self.histogram.enable_covariance(param.value())
            if param.value():
                self._cov_dock.show()
                self.get_action('show_covariance').setChecked(True)
            else:
                self._cov_dock.hide()
                self.get_action('show_covariance').setChecked(False)
        elif name == 'refresh_rate_s':
            if self.is_acquiring:
                self.refresh_timer.start(int(param.value() * 1000))
        elif name == 'clear_interval':
            if self.is_acquiring and param.value() > 0:
                self._last_clear_time = time.time()
        elif name == 'colormap':
            self._on_colormap_changed(param.value())
        elif name == 'display_fraction':
            frac = param.value() / 100.0
            self.histogram.set_display_fraction(frac)
            if self.pipeline_thread is not None:
                self.pipeline_thread.set_display_fraction(frac)
        elif name == 'max_time_window_s':
            self._apply_timeseries_window(param.value())
        elif name in ('enabled', 'coeff', 't0', 'mass_min', 'mass_max', 'mass_bins'):
            self._on_mass_calib_changed()

    # =========================================================================
    # Display parameter — convenience property
    # =========================================================================
    @property
    def display(self):
        """Shortcut to the mass calibration Parameter group in settings."""
        return self.settings.child('display_settings', 'mass_calib')

    # =========================================================================
    # Status bar LEDs
    # =========================================================================
    def _build_status_leds(self):
        for name, label in [('led_connected', 'SERVAL'),
                             ('led_acquiring', 'ACQ'),
                             ('led_recording', 'REC')]:
            led = QLabel(f'● {label}')
            led.setStyleSheet('color: #555555; font-weight: bold; padding: 0 6px;')
            self.status_bar.addPermanentWidget(led)
            setattr(self, name, led)

    def _set_led(self, led: QLabel, active: bool, color: str = '#44cc44'):
        col = color if active else '#555555'
        led.setStyleSheet(f'color: {col}; font-weight: bold; padding: 0 6px;')

    # =========================================================================
    # ActionManager
    # =========================================================================
    def setup_actions(self):
        self.add_action('show_settings', 'Settings', 'settings',
                        tip='Show/hide settings panel',
                        checkable=True, checked=True, shortcut='F1', auto_toolbar=False,
                        icon_checked_color='green')
        self.add_action('connect', 'Connect', 'cable',
                        tip='Connect / Disconnect SERVAL',
                        checkable=True, shortcut='F2', auto_toolbar=False,
                        icon_checked_color='green')
        self.add_action('run', 'Run', 'motion_play',
                        tip='Start / Stop acquisition', shortcut='F5', auto_toolbar=False,
                        checkable=True, icon_checked_color='green')
        self.add_action('show_tof_dock', 'TOF', 'bar_chart',
                        tip='Show/hide the TOF histogram dock',
                        checkable=True, checked=True, auto_toolbar=False,
                        icon_checked_color='green')
        self.add_action('show_total_dock', 'Image', 'image',
                        tip='Show/hide the Total 2D image dock',
                        checkable=True, checked=True, auto_toolbar=False,
                        icon_checked_color='green')
        self.add_action('show_recording', 'Recording', 'hard_drive',
                        tip='Show/hide recording controls',
                        checkable=True, checked=False, auto_toolbar=False,
                        icon_checked_color='green')
        self.add_action('show_log', 'Log', 'format_list_bulleted',
                        tip='Show/hide log panel',
                        checkable=True, auto_toolbar=False,
                        icon_checked_color='green')
        self.add_action('show_pipeline_status', 'Status', 'analytics',
                        tip='Show/hide pipeline status panel (queues & workers)',
                        checkable=True, auto_toolbar=False,
                        icon_checked_color='green')
        self.add_action('show_covariance', 'Covariance', 'grid_on',
                        tip='Show/hide the per-shot covariance map dock',
                        checkable=True, auto_toolbar=False,
                        icon_checked_color='green')
        self.add_action('quit', 'Quit', 'close',
                        tip='Close the application',
                        auto_toolbar=False)

    def _setup_toolbar(self):
        self.setup_actions()
        tb = self.addToolBar('Acquisition')
        tb.setMovable(False)

        tb.addAction(self.get_action('show_settings'))
        tb.addSeparator()
        tb.addAction(self.get_action('connect'))
        tb.addSeparator()
        tb.addAction(self.get_action('run'))
        tb.addSeparator()
        tb.addAction(self.get_action('show_tof_dock'))
        tb.addAction(self.get_action('show_total_dock'))
        tb.addSeparator()
        tb.addAction(self.get_action('show_recording'))
        tb.addAction(self.get_action('show_log'))
        tb.addAction(self.get_action('show_pipeline_status'))
        tb.addAction(self.get_action('show_covariance'))
        tb.addSeparator()
        tb.addAction(self.get_action('quit'))

        self.get_action('run').setEnabled(False)

        # Spacer pushes the view-options button to the far right
        spacer = QWidget()
        spacer.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Preferred)
        tb.addWidget(spacer)

        self._build_toolbar_style_button(tb)

        self.get_action('show_settings').connect_to(
            lambda v: self._settings_dock.show() if v else self._settings_dock.hide())
        self.get_action('connect').connect_to(self._on_connect_clicked)
        self.get_action('run').connect_to(self._on_run_clicked)
        self.get_action('show_tof_dock').connect_to(
            lambda v: self.tof_dock.show() if v else self.tof_dock.hide())
        self.get_action('show_total_dock').connect_to(
            lambda v: self.total_dock.show() if v else self.total_dock.hide())
        self.get_action('show_recording').connect_to(
            lambda v: self._recording_toolbar.setVisible(v))
        self.get_action('show_log').connect_to(
            lambda v: self.log_dock.show() if v else self.log_dock.hide())
        self.get_action('show_pipeline_status').connect_to(
            lambda v: self._status_dock.show() if v else self._status_dock.hide())
        self.get_action('show_covariance').connect_to(
            lambda v: self._cov_dock.show() if v else self._cov_dock.hide())
        self.get_action('quit').connect_to(lambda: self.close())

    # ── Toolbar style ─────────────────────────────────────────────────────────

    _TOOLBAR_STYLES = [
        ('Icons only',        Qt.ToolButtonStyle.ToolButtonIconOnly),
        ('Text only',         Qt.ToolButtonStyle.ToolButtonTextOnly),
        ('Text beside icons', Qt.ToolButtonStyle.ToolButtonTextBesideIcon),
        ('Text under icons',  Qt.ToolButtonStyle.ToolButtonTextUnderIcon),
        ('System settings',  Qt.ToolButtonStyle.ToolButtonFollowStyle),
    ]

    def _apply_toolbar_style(self, style: Qt.ToolButtonStyle):
        """Apply *style* to every QToolBar in the application and persist it."""
        from qtpy.QtWidgets import QToolBar as _QToolBar
        for widget in QApplication.instance().allWidgets():
            if isinstance(widget, _QToolBar):
                widget.setToolButtonStyle(style)
        # .value handles Qt6 enums; plain int() covers Qt5 sip ints
        style_int = style.value if hasattr(style, 'value') else int(style)
        self._qsettings().setValue('toolbar_style', style_int)

    def _build_toolbar_style_button(self, tb):
        """Add a view-options QToolButton (far right) for toolbar display style."""
        btn = QToolButton()
        btn.setIcon(create_icon('explicit'))
        btn.setToolTip("Toolbar display style")
        btn.setPopupMode(QToolButton.ToolButtonPopupMode.InstantPopup)

        menu = QMenu(btn)
        self._toolbar_style_group = QActionGroup(menu)
        self._toolbar_style_group.setExclusive(True)

        for label, style in self._TOOLBAR_STYLES:
            act = menu.addAction(label)
            act.setCheckable(True)
            act.setActionGroup(self._toolbar_style_group)
            act.triggered.connect(
                lambda _checked, s=style: self._apply_toolbar_style(s))

        btn.setMenu(menu)
        tb.addWidget(btn)

    # =========================================================================
    # UI Setup
    # =========================================================================
    def _setup_ui(self):
        # DockArea as central widget
        self.dock_area = DockArea()
        self.setCentralWidget(self.dock_area)

        # Left: Settings
        self._create_settings_dock()

        # Centre: TOF histogram dock
        self.tof_dock = TofHistogramDock()
        self.dock_area.addDock(self.tof_dock, 'right', self._settings_dock)

        # Right: Total 2D image
        self.total_dock = ImageDockWidget("Total", closable=False)
        self.dock_area.addDock(self.total_dock, 'right', self.tof_dock)
        self.total_roi_manager = SpatialROIManager("", self.total_dock, self)

        # Covariance map (hidden by default, tabbed with total_dock)
        self._cov_dock = CovarianceDock()
        self.dock_area.addDock(self._cov_dock, 'above', self.total_dock)
        self._cov_dock.hide()

        # Bottom: Log (hidden by default)
        self.log_dock = LogDock()
        self.dock_area.addDock(self.log_dock, 'bottom')
        self.log_dock.hide()
        add_log_handler(self.log_dock.handler)

        # Bottom: Pipeline status (hidden by default)
        self._status_dock = PipelineStatusDock()
        self.dock_area.addDock(self._status_dock, 'bottom')
        self._status_dock.hide()

        # ROI manager (composition, not inheritance)
        self.roi_manager = ROIManager(
            tof_plot=self.tof_dock.tof_plot,
            roi_table=self.tof_dock.roi_table,
            main_window=self,
            dock_area=self.dock_area,
            total_dock=self.total_dock,
            parent=self,
        )

    def _create_settings_dock(self):
        self._settings_dock = Dock("Settings", closable=False, size=(350, 800))
        widget = QWidget()
        layout = QVBoxLayout(widget)
        layout.setContentsMargins(5, 5, 5, 5)
        layout.addWidget(self.settings_tree, stretch=1)
        self._settings_dock.addWidget(widget)
        self.dock_area.addDock(self._settings_dock, 'left')

    def _create_recording_toolbar(self):
        self.addToolBarBreak(Qt.ToolBarArea.TopToolBarArea)
        tb = QToolBar("Recording", self)
        tb.setObjectName('recording_toolbar')
        self.addToolBar(Qt.ToolBarArea.TopToolBarArea, tb)

        tb.addWidget(QLabel("  Name:"))
        self.record_filename_edit = QLineEdit()
        self.record_filename_edit.setPlaceholderText("auto-timestamp")
        self.record_filename_edit.setToolTip("Save filename (no extension)")
        self.record_filename_edit.setMinimumWidth(160)
        tb.addWidget(self.record_filename_edit)

        self.auto_increment_check = QCheckBox("Auto-increment")
        self.auto_increment_check.setToolTip(
            "After a recording finishes, prefill the next name by incrementing "
            "its trailing number (e.g. run_007 -> run_008)")
        tb.addWidget(self.auto_increment_check)

        tb.addWidget(QLabel("  Duration (s):"))
        self.save_duration_spin = QDoubleSpinBox()
        self.save_duration_spin.setRange(0.0, 86400.0)
        self.save_duration_spin.setSingleStep(0.5)
        self.save_duration_spin.setValue(0.0)
        self.save_duration_spin.setDecimals(1)
        self.save_duration_spin.setToolTip("0 = manual stop")
        self.save_duration_spin.setSpecialValueText("Manual")
        self.save_duration_spin.setFixedWidth(90)
        tb.addWidget(self.save_duration_spin)

        self.record_btn = QPushButton("Save")
        self.record_btn.clicked.connect(self._on_save_clicked)
        self.record_btn.setEnabled(False)
        self.record_btn.setFixedWidth(70)
        tb.addWidget(self.record_btn)

        tb.addSeparator()
        self.record_time_label = QLabel("")
        self.record_time_label.setStyleSheet("font-family: monospace; color: #ff4444; font-weight: bold;")
        tb.addWidget(self.record_time_label)

        tb.addSeparator()
        self.stats_label = QLabel("Events: 0")
        self.stats_label.setStyleSheet("font-family: monospace;")
        tb.addWidget(self.stats_label)

        self._recording_toolbar = tb

    # =========================================================================
    # Signal Connections
    # =========================================================================
    def _connect_signals(self):
        # SERVAL controller
        self.settings.child("serval", "serval_connection").sigActivated.connect(
            self._on_connect_clicked)
        self.settings.child("serval", "voltage_settings").sigActivated.connect(
            self._on_apply_bias)
        self.settings.child("serval", "trigger_settings").sigActivated.connect(
            self._on_apply_triggers)
        self.serval.connected.connect(self._on_serval_connected)
        self.serval.disconnected.connect(self._on_serval_disconnected)
        self.serval.error_occurred.connect(self._on_serval_error)

        # Viewer dock Clear buttons — all route to the same full reset
        self.tof_dock.clear_requested.connect(self._on_clear_all)
        self.total_dock.clear_requested.connect(self._on_clear_all)
        self._cov_dock.clear_requested.connect(self._on_clear_all)
        self.roi_manager.clear_requested.connect(self._on_clear_all)
        self.roi_manager.dock_created.connect(self._on_roi_dock_created)
        self.tof_dock.tof_bin_spec_changed.connect(self._on_tof_bin_spec_changed)
        self._cov_dock.cov_bin_spec_changed.connect(self._on_cov_bin_spec_changed)

        # ROI dock mini-toolbar → ROIManager
        self.tof_dock.add_roi_clicked.connect(self.roi_manager.add_roi)
        self.tof_dock.remove_roi_clicked.connect(self.roi_manager.remove_roi)
        self.tof_dock.raise_roi_clicked.connect(self.roi_manager.raise_selected)
        self.tof_dock.zoom_roi_clicked.connect(self.roi_manager.zoom_to_selected)
        self.tof_dock.zoom_out_clicked.connect(self.roi_manager.zoom_out)

        # ROIManager data-flow → HistogramController
        self.roi_manager.roi_added.connect(
            lambda name, mn, mx: self.histogram.add_roi(name, mn, mx))
        self.roi_manager.roi_removed.connect(self.histogram.remove_roi)
        self.roi_manager.roi_changed.connect(self.histogram.update_roi)

        # Spatial ROIs on the Total dock's own image
        self.total_roi_manager.roi_added.connect(self.histogram.add_spatial_roi)
        self.total_roi_manager.roi_removed.connect(self.histogram.remove_spatial_roi)
        self.total_roi_manager.roi_changed.connect(self.histogram.update_spatial_roi)

        # Spatial ROI TOF overlay curves in the TOF dock
        self.total_roi_manager.roi_added.connect(self._on_total_spatial_roi_added)
        self.total_roi_manager.roi_removed.connect(self._on_total_spatial_roi_removed)

        # Spatial ROIs nested inside each TOF-ROI's own dock
        self.roi_manager.spatial_roi_added.connect(self.histogram.add_spatial_roi)
        self.roi_manager.spatial_roi_removed.connect(self.histogram.remove_spatial_roi)
        self.roi_manager.spatial_roi_changed.connect(self.histogram.update_spatial_roi)
        self.roi_manager.spatial_rois_cleared.connect(self.histogram.remove_spatial_rois_for_parent)

    # =========================================================================
    # Spatial-ROI TOF overlay handlers
    # =========================================================================
    def _on_total_spatial_roi_added(self, parent, name, shape, op, x, y, w, h):
        if parent != "":
            return
        color = self.total_roi_manager.get_roi_color(name)
        if color is not None:
            self.tof_dock.add_spatial_tof_curve(name, color)

    def _on_total_spatial_roi_removed(self, parent, name):
        if parent != "":
            return
        self.tof_dock.remove_spatial_tof_curve(name)
        if not self.total_roi_manager.get_roi_names():
            self.tof_dock.remove_combined_tof_curve()

    # =========================================================================
    # Display parameter changes
    # =========================================================================
    def _on_clear_all(self):
        self.histogram.clear()
        self.histogram.clear_timeseries()
        self._cov_dock.clear()
        self._update_histograms()
        self._log("Histograms and time series cleared")

    def _on_roi_dock_created(self, dock):
        """Apply current display settings to a newly created ROI dock."""
        max_s = self.settings.child(
            'display_settings', 'live_feed', 'max_time_window_s').value()
        dock.set_time_window(max_s)

    def _apply_timeseries_window(self, max_s: float):
        """Push a trailing time-window to every counts/shot timeseries plot."""
        for dock in [self.total_dock] + self.roi_manager.docks:
            dock.set_time_window(max_s)

    def _on_colormap_changed(self, name: str):
        self.total_dock.set_colormap(name)
        self.roi_manager.set_colormap(name)

    def _on_tof_bin_spec_changed(self):
        spec = self.tof_dock.tof_bin_spec()
        if spec is None:
            return
        self.histogram.set_tof_config(tof_range=(spec.start, spec.end), tof_bins=spec.n_bins)
        self._cov_dock.set_tof_range(spec.start, spec.end)
        self._update_histograms()

    def _on_cov_bin_spec_changed(self):
        spec = self._cov_dock.cov_bin_spec()
        if spec is None:
            return
        self.histogram.set_covariance_config(bins=spec.n_bins, cov_range=(spec.start, spec.end))
        self._cov_dock.clear()
        self._update_histograms()

    def _on_mass_calib_changed(self):
        calib = self.display
        coeff   = calib.child('coeff').value()
        t0      = calib.child('t0').value()
        enabled = calib.child('enabled').value()
        self.histogram.set_mass_calibration(coeff, t0, enabled=enabled)
        self.histogram.set_mass_config(
            mass_range=(calib.child('mass_min').value(), calib.child('mass_max').value()),
            mass_bins=calib.child('mass_bins').value(),
        )
        self.roi_manager.update_mass_calibration(coeff, t0, enabled)
        self._cov_dock.set_axis_label("m/z" if enabled else "TOF (ns)")
        self._apply_display_mode(self._display_mode)
        self._update_histograms()

    def _apply_display_mode(self, mode: str):
        """Update plot titles and axis labels to match display mode."""
        self._display_mode = mode
        mass_mode = self.histogram.is_mass_calibration_enabled()
        if mode == 'pixels':
            base_title, base_units = "Time of Arrival (TOA)", "TOA (ns)"
            ts_label = "Counts/Refresh"
            curve_label = "TOA"
        else:
            base_title, base_units = "Time of Flight (TOF)", "TOF (ns)"
            ts_label = "Counts/Shot"
            curve_label = "m/z (all)" if mass_mode else "TOF (all)"
        if mass_mode:
            self.tof_dock.set_plot_title(f"{base_title} → Mass (calibrated)")
            self.tof_dock.set_x_label("m/z")
        else:
            self.tof_dock.set_plot_title(base_title)
            self.tof_dock.set_x_label(base_units)
        self.tof_dock.set_main_curve_label(curve_label)
        self.total_dock.set_timeseries_label(ts_label)
        self.roi_manager.set_timeseries_label(ts_label)

    # =========================================================================
    # SERVAL Handlers
    # =========================================================================
    def _on_connect_clicked(self):
        if self.serval.is_connected:
            self.serval.disconnect()
        else:
            host = self.settings.child('serval', 'serval_connection', 'host').value()
            port = self.settings.child('serval', 'serval_connection', 'port').value()
            self.serval.host = host
            self.serval.port = port
            self.serval.base_url = f'http://{host}:{port}'
            self._log(f"Connecting to {host}:{port}...")
            self.serval.connect()

    def _on_serval_connected(self):
        self.settings.child('serval', 'serval_connection').setValue(self.serval.is_connected)
        self.get_action('connect').setChecked(True)
        self.get_action('run').setEnabled(True)
        self._set_led(self.led_connected, True)
        if self.is_acquiring:
            self.record_btn.setEnabled(True)
        self._log("Connected to SERVAL")

    def _on_serval_disconnected(self):
        self.settings.child('serval', 'serval_connection').setValue(self.serval.is_connected)
        self.get_action('connect').setChecked(False)
        self.get_action('run').setEnabled(False)
        self._set_led(self.led_connected, False)
        self.record_btn.setEnabled(False)
        self._log("Disconnected from SERVAL")

    def _on_serval_error(self, msg: str):
        self._log(f"SERVAL error: {msg}", level=40)

    def _on_apply_bias(self):
        s = self.settings.child('serval', 'voltage_settings')
        voltage = s['bias_voltage']
        enabled = s['bias_enabled']
        success = self.serval.set_bias(voltage, enabled)
        self._log(f"Bias: {voltage}V (enabled={enabled})" if success
                  else "Failed to set bias", level=20 if success else 40)
        s.setValue(success)

    def _on_apply_triggers(self):
        s = self.settings.child('serval', 'trigger_settings')
        mode       = s['trigger_mode']
        n_triggers = s['n_triggers']
        period     = s['trigger_period']
        exposure   = s['trigger_exposure']
        success = self.serval.set_trigger_settings(mode, n_triggers, period, exposure)
        self._log(f"Triggers set: {mode}" if success
                  else "Failed to set triggers", level=20 if success else 40)
        s.setValue(success)

    # =========================================================================
    # Pipeline Status — delegated to PipelineStatusDock
    # =========================================================================
    def _on_status_update(self, status_dict: dict):
        self._status_dock.update_throughput(status_dict)

    def _update_pipeline_status(self):
        if self.pipeline_thread is not None:
            self._status_dock.update_queues_and_workers(
                self.pipeline_thread.get_live_status())

    def _reset_pipeline_status(self):
        self._status_dock.reset()

    # =========================================================================
    # Acquisition Control  →  see pipeline_mixin.py
    # =========================================================================
    # =========================================================================
    # Data Handlers
    # =========================================================================
    def _on_event_data(self, event_num, x, y, tof, tot, t_sent):
        if self._display_mode != 'events':
            return
        self._lag_ms = (time.monotonic() - t_sent) * 1000
        self.histogram.add_events(event_num, x, y, tof, tot)

    def _on_pixel_data(self, x, y, toa, tot, t_sent):
        if self._display_mode != 'pixels':
            return
        self._lag_ms = (time.monotonic() - t_sent) * 1000
        self.histogram.add_pixels(x, y, toa, tot)

    def _update_histograms(self):
        t_start = time.perf_counter()

        if self.is_acquiring:
            self.histogram.sample_timeseries()
        t_timeseries = time.perf_counter()

        pixel_data   = self.histogram.get_pixel_image()
        total_counts = int(pixel_data.sum())
        self.total_dock.update_image(pixel_data)
        self.total_dock.update_counts(total_counts)
        if self.total_dock.is_timeseries_visible():
            times, counts = self.histogram.get_timeseries(None)
            self.total_dock.update_timeseries(times, counts)
        t_image = time.perf_counter()

        self.roi_manager.update_displays(self.histogram, total_counts)
        self.total_roi_manager.update_displays(self.histogram, total_counts)
        t_roi = time.perf_counter()

        if self.histogram.is_mass_calibration_enabled():
            tof_centers, tof_counts = self.histogram.get_mass_histogram()
        else:
            tof_centers, tof_counts = self.histogram.get_tof_histogram()
        self.tof_dock.update_tof(tof_centers, tof_counts)

        # Update spatially-filtered TOF overlay curves
        mass_mode = self.histogram.is_mass_calibration_enabled()
        spatial_names = self.total_roi_manager.get_roi_names()
        for name in spatial_names:
            centers, counts = self.histogram.get_spatial_roi_tof("", name)
            if mass_mode:
                calib = self.display
                coeff = calib.child('coeff').value() or 1.0
                t0    = calib.child('t0').value()
                centers = np.clip((centers - t0) / coeff, 0.0, None) ** 2
            self.tof_dock.update_spatial_tof_curve(name, centers, counts)
        if spatial_names:
            centers, counts = self.histogram.get_combined_tof("")
            if mass_mode:
                calib = self.display
                coeff = calib.child('coeff').value() or 1.0
                t0    = calib.child('t0').value()
                centers = np.clip((centers - t0) / coeff, 0.0, None) ** 2
            self.tof_dock.update_combined_tof_curve(centers, counts)

        t_tof = time.perf_counter()

        stats = self.histogram.get_stats()
        lag_str = f"{self._lag_ms:.0f} ms" if self._lag_ms is not None else "—"
        self.stats_label.setText(
            f"Events: {stats['total_events']:,} | Total: {stats['pixel_sum']:,} | Lag: {lag_str}")

        if self._is_recording and self._record_start_time is not None:
            elapsed = int(time.monotonic() - self._record_start_time)
            h, rem = divmod(elapsed, 3600)
            m, s = divmod(rem, 60)
            self.record_time_label.setText(f"● Rec {h:02d}:{m:02d}:{s:02d}")

        if self.settings.child('display_settings', 'covariance', 'cov_enabled').value():
            centers_ns, cov, corr, n_shots = self.histogram.get_covariance_map()
            if self.histogram.is_mass_calibration_enabled():
                calib = self.display
                coeff = calib.child('coeff').value() or 1.0
                t0    = calib.child('t0').value()
                centers = np.clip((centers_ns - t0) / coeff, 0, None) ** 2
            else:
                centers = centers_ns
            self._cov_dock.update_map(centers, cov, corr, n_shots)
        t_cov = time.perf_counter()

        self._update_pipeline_status()
        t_status = time.perf_counter()

        if self.is_acquiring and self._last_clear_time is not None:
            clear_interval = self.settings.child('display_settings', 'live_feed', 'clear_interval').value()
            if clear_interval > 0 and (time.time() - self._last_clear_time) >= clear_interval:
                self.histogram.clear()
                self._last_clear_time = time.time()
                self._log("Histograms cleared")

        total_ms = (t_status - t_start) * 1000
        if total_ms > _SLOW_REFRESH_MS:
            self._gui_logger.debug(
                f"_update_histograms: {total_ms:.1f} ms total "
                f"(timeseries {(t_timeseries - t_start) * 1000:.1f}, "
                f"image {(t_image - t_timeseries) * 1000:.1f}, "
                f"roi {(t_roi - t_image) * 1000:.1f}, "
                f"tof {(t_tof - t_roi) * 1000:.1f}, "
                f"cov {(t_cov - t_tof) * 1000:.1f}, "
                f"status {(t_status - t_cov) * 1000:.1f})")

    # Session persistence  →  see session_mixin.py

    # =========================================================================
    # Window Events
    # =========================================================================
    def _log(self, msg: str, level: int = 20):
        self.status_bar.showMessage(msg)
        self._gui_logger.log(level, msg)

    def closeEvent(self, event):
        if self.is_acquiring:
            reply = QMessageBox.question(
                self, "Acquisition Running",
                "Stop acquisition and exit?",
                QMessageBox.StandardButton.Yes | QMessageBox.StandardButton.No,
                QMessageBox.StandardButton.No,
            )
            if reply == QMessageBox.StandardButton.No:
                event.ignore()
                return
            self._on_stop_clicked()
            if self.pipeline_thread:
                self.pipeline_thread.wait(5000)

        self._save_session()
        remove_log_handler(self.log_dock.handler)
        event.accept()


def main():
    import multiprocessing
    multiprocessing.set_start_method('forkserver', force=False)

    app = QApplication(sys.argv)
    app.setStyle('Fusion')
    window = ServalAcquisitionGUI()
    window.show()
    sys.exit(app.exec_())


if __name__ == "__main__":
    main()
